#!/usr/bin/env bash
# Generated by pivota-spec init-dev-server
# Catalog entry: agent-synthesized
# Generator version: init-dev-server@1
#
# Edits ABOVE the END PIVOTA PREAMBLE marker are reset on regen.
# Edits BELOW the marker are preserved on regen.
#
# Why these choices (decision-trace; do not delete):
#   - `set -euo pipefail` not just `-e` — RESEARCH.md Pitfall 4 (silent pipe failures).
#   - `sha256sum` for lockfile hashing — RESEARCH.md "Don't hand-roll" (universal
#     coreutils, no extra dep vs blake3 / git hash-object / md5sum).
#   - Backoff 1s / 2s / 4s — Claude's Discretion per CONTEXT.md (small base, predictable).
#   - Log destination `/tmp/pivota-dev.log` — Open Question #4 resolved (always
#     writable inside Daytona sandboxes; matches existing convention).
#   - Lockfile-sentinel skip combined with INSTALL_PRESENCE_CHECK — RESEARCH.md
#     Pitfall 6 (sentinel survives reboots but install output dirs may not on
#     fresh tmpfs; never skip on a clean directory).
#   - Retry exits with INNER command's last exit code (not a fixed 1) so callers
#     can disambiguate failures from the wrapper.
#   - DB_CONTRACT branch: if PIVOTA_DB_MODE or DATABASE_URL is injected, this is a
#     native-sidecar K8s sandbox — run Spring Boot directly against the injected PG
#     sidecar. Otherwise (Daytona / self-provided) Docker is available — run
#     docker compose up. See runtime-environment.md §3 and §6.
#   - No mvnw in backend/ — pre-exec installs system Java 21 + Maven via apt-get,
#     matching the JDK_INSTALL_SNIPPET pattern from project_preview_service.rs.
#   - SERVER_ADDRESS=0.0.0.0: Spring Boot reads server.address from this env var
#     so the preview iframe can reach port 8080 from outside the sandbox loopback.
#   - SPRING_DATASOURCE_URL: Spring Boot / HikariCP requires a jdbc:postgresql://
#     URL. Platform may inject DATABASE_URL as postgresql://, postgres://, or
#     mysql:// (PIVOTA_DB_MODE=sidecar-mysql). The mysql:// case is handled by
#     constructing jdbc:postgresql:// from PG* env vars or falling back to the
#     application.yml default — the MySQL URL is never passed to org.postgresql.Driver.
#   - Flyway is declared in pom.xml and will run DB migrations automatically on
#     Spring context startup (spring.flyway.enabled=true by default) — no separate
#     migration step needed here; it runs before the app starts serving requests.

set -euo pipefail

# === Bash version guard (RESEARCH.md Pitfall 8) ===
# `wait -n` (used by the multi-process variant) requires bash >= 4.3.
# Fail fast with a clear message; do not silently degrade.
if (( BASH_VERSINFO[0] < 4 )) || { (( BASH_VERSINFO[0] == 4 )) && (( BASH_VERSINFO[1] < 3 )); }; then
  echo "[pivota] bash 4.3+ required for 'wait -n'; found ${BASH_VERSION}" >&2
  exit 127
fi

# === D-11.4: tee stdout/stderr to /tmp/pivota-dev.log AND pass through ===
mkdir -p /tmp
exec > >(tee -a /tmp/pivota-dev.log) 2>&1
echo "[pivota] $(date -Iseconds) start-dev.sh begin (catalog: agent-synthesized)"

# === Detect DB contract (runtime-environment.md §3) ===
# native-sidecar: platform injects DATABASE_URL / PIVOTA_DB_MODE → run Spring Boot directly.
# self-provided: Daytona with Docker/DinD → run docker compose up.
if [[ -n "${PIVOTA_DB_MODE:-}" || -n "${DATABASE_URL:-}" ]]; then
  DB_CONTRACT="native-sidecar"
  echo "[pivota] DB_CONTRACT=native-sidecar (PIVOTA_DB_MODE=${PIVOTA_DB_MODE:-unset})"
else
  DB_CONTRACT="self-provided"
  echo "[pivota] DB_CONTRACT=self-provided (Daytona/DinD — will use docker compose up)"
fi

# === D-11.1 + D-11.2: per-stack 0.0.0.0 binding + host allowlist relaxation ===
# Spring Boot reads SERVER_ADDRESS as the bind override (env-var form of server.address).
# No host-allowlist check in Spring Boot — only bind address matters.
export SERVER_ADDRESS=0.0.0.0

# === D-11.3: .env.example -> .env seed (platform-injection-safe) ===
# Seed .env from .env.example for first boot, but NEVER let an .env.example
# placeholder shadow a variable the platform already injected into the sandbox
# environment (DATABASE_URL, POSTGRES_*/MYSQL_*, REDIS_URL, PIVOTA_*, PORT, etc.).
if [[ ! -f .env && -f .env.example ]]; then
  echo "[pivota] seeding .env from .env.example (preserving platform-injected vars)"
  while IFS= read -r line || [[ -n "$line" ]]; do
    trimmed="${line#"${line%%[![:space:]]*}"}"   # left-trim for the test only
    if [[ "$trimmed" == \#* || -z "$trimmed" || "$trimmed" != *"="* ]]; then
      printf '%s\n' "$line"; continue            # keep comments / blanks / non-assignments
    fi
    key="${trimmed#export }"; key="${key%%=*}"; key="${key//[[:space:]]/}"
    if [[ -n "${!key+x}" ]]; then
      printf '# [pivota] %s omitted — provided by platform environment\n' "$key"
    else
      printf '%s\n' "$line"
    fi
  done < .env.example > .env
fi

# === Self-provided path: Daytona DinD — run docker compose up ===
# On Daytona, Docker is available and the compose file IS how the app + DB runs.
# Do not run Spring Boot directly; let compose handle orchestration.
if [[ "$DB_CONTRACT" == "self-provided" ]]; then
  echo "[pivota] self-provided path: launching via docker compose up"
  EXEC_CMD='docker compose up'
  ATTEMPT=1
  DELAY=1
  while (( ATTEMPT <= 3 )); do
    echo "[pivota] attempt $ATTEMPT: $EXEC_CMD"
    if bash -c "$EXEC_CMD"; then
      echo "[pivota] inner command exited 0; propagating success"
      exit 0
    fi
    EXIT_CODE=$?
    if (( ATTEMPT == 3 )); then
      echo "[pivota] all 3 attempts failed (last exit=$EXIT_CODE); surfacing failure"
      exit "$EXIT_CODE"
    fi
    echo "[pivota] attempt $ATTEMPT failed (exit=$EXIT_CODE); retrying in ${DELAY}s"
    sleep "$DELAY"
    DELAY=$(( DELAY * 2 ))
    ATTEMPT=$(( ATTEMPT + 1 ))
  done
  exit 1
fi

# === Native-sidecar path: K8s / Local — run Spring Boot directly ===
# No Docker daemon available. Platform injects a PostgreSQL sidecar and DATABASE_URL.

# --- Pre-exec: install Java 21 + Maven if missing ---
# (RESEARCH.md Pitfall 7: Daytona base snapshot does not ship OpenJDK)
if ! command -v java >/dev/null 2>&1 || ! java -version 2>&1 | grep -q 'version "21'; then
  echo "[pivota] Java 21 not found — installing via apt-get (one-time, ~30s)"
  export DEBIAN_FRONTEND=noninteractive
  sudo apt-get update -qq
  sudo apt-get install -y -qq openjdk-21-jdk-headless
  export JAVA_HOME
  JAVA_HOME=$(readlink -f "$(command -v java)" 2>/dev/null | sed -E 's|/bin/java$||')
  export PATH="$JAVA_HOME/bin:$PATH"
  echo "[pivota] JAVA_HOME=$JAVA_HOME"
fi

if ! command -v mvn >/dev/null 2>&1; then
  echo "[pivota] Maven not found — installing via apt-get"
  export DEBIAN_FRONTEND=noninteractive
  sudo apt-get update -qq
  sudo apt-get install -y -qq maven
fi

# --- Construct SPRING_DATASOURCE_URL from injected DATABASE_URL ---
# Spring Boot / HikariCP requires jdbc:postgresql:// scheme.
# Platform injects DATABASE_URL (may be postgresql://, postgres://, or sidecar-mysql mysql:// prefix).
if [[ -n "${DATABASE_URL:-}" ]]; then
  if [[ "${DATABASE_URL}" == jdbc:postgresql://* ]]; then
    export SPRING_DATASOURCE_URL="${DATABASE_URL}"
    echo "[pivota] SPRING_DATASOURCE_URL set from DATABASE_URL (already jdbc: scheme)"
  elif [[ "${DATABASE_URL}" == postgresql://* || "${DATABASE_URL}" == postgres://* ]]; then
    # Convert postgresql://user:pass@host:port/db to jdbc:postgresql://host:port/db?user=...&password=...
    _stripped="${DATABASE_URL#postgresql://}"
    _stripped="${_stripped#postgres://}"
    if [[ "$_stripped" == *"@"* ]]; then
      _userpass="${_stripped%%@*}"
      _hostpart="${_stripped#*@}"
      _user="${_userpass%%:*}"
      _pass="${_userpass#*:}"
      export SPRING_DATASOURCE_URL="jdbc:postgresql://${_hostpart}?user=${_user}&password=${_pass}"
    else
      export SPRING_DATASOURCE_URL="jdbc:postgresql://${_stripped}"
    fi
    echo "[pivota] SPRING_DATASOURCE_URL normalized from DATABASE_URL"
  elif [[ "${DATABASE_URL}" == mysql://* || "${DATABASE_URL}" == mysql+*://* ]]; then
    # Platform injected a MySQL sidecar URL (PIVOTA_DB_MODE=sidecar-mysql).
    # This Spring Boot app is PostgreSQL-only (org.postgresql.Driver, tsvector, GIN indexes).
    # Ignore the MySQL URL entirely and construct a PostgreSQL JDBC URL from PG* env vars.
    # If PG* vars are not set, leave SPRING_DATASOURCE_URL unset so application.yml default
    # (jdbc:postgresql://localhost:5432/ureport) applies via ${DATABASE_URL:...} fallback.
    echo "[pivota] WARNING: DATABASE_URL is MySQL scheme (PIVOTA_DB_MODE=${PIVOTA_DB_MODE:-unset})"
    echo "[pivota] This stack is PostgreSQL-only — ignoring MySQL URL, constructing PostgreSQL JDBC URL"
    _PG_HOST="${PGHOST:-}"
    _PG_PORT="${PGPORT:-5432}"
    _PG_DB="${PGDATABASE:-ureport}"
    _PG_USER="${PGUSER:-}"
    _PG_PASS="${PGPASSWORD:-}"
    if [[ -n "$_PG_HOST" ]]; then
      # PG* sidecar vars are available — construct the full JDBC URL
      if [[ -n "$_PG_USER" && -n "$_PG_PASS" ]]; then
        export SPRING_DATASOURCE_URL="jdbc:postgresql://${_PG_HOST}:${_PG_PORT}/${_PG_DB}?user=${_PG_USER}&password=${_PG_PASS}"
      elif [[ -n "$_PG_USER" ]]; then
        export SPRING_DATASOURCE_URL="jdbc:postgresql://${_PG_HOST}:${_PG_PORT}/${_PG_DB}?user=${_PG_USER}"
      else
        export SPRING_DATASOURCE_URL="jdbc:postgresql://${_PG_HOST}:${_PG_PORT}/${_PG_DB}"
      fi
      echo "[pivota] SPRING_DATASOURCE_URL constructed from PG* vars: jdbc:postgresql://${_PG_HOST}:${_PG_PORT}/${_PG_DB}?<credentials-redacted>"
    else
      # No PG* vars — leave SPRING_DATASOURCE_URL unset.
      # application.yml default: ${DATABASE_URL:jdbc:postgresql://localhost:5432/ureport}
      # Since DATABASE_URL is set (but MySQL), Spring will try to use it unless we override.
      # Export the PostgreSQL default explicitly so HikariCP never sees the mysql:// URL.
      export SPRING_DATASOURCE_URL="jdbc:postgresql://localhost:5432/ureport"
      echo "[pivota] No PG* vars found — using application.yml default: jdbc:postgresql://localhost:5432/ureport"
    fi
  else
    # Truly unknown scheme — pass through so Spring/Flyway can surface the error clearly.
    export SPRING_DATASOURCE_URL="${DATABASE_URL}"
    echo "[pivota] WARNING: DATABASE_URL scheme unrecognized — passed as-is to SPRING_DATASOURCE_URL"
  fi
fi

# --- Flyway note ---
# pom.xml declares flyway-core + flyway-database-postgresql. Spring Boot auto-runs
# Flyway migrations on startup (spring.flyway.enabled=true by default). No explicit
# migration command needed here — Flyway runs before the app starts serving requests.
# If migrations fail, Spring context startup fails and the retry loop re-attempts.

# === D-12: idempotent install via lockfile hash + presence check ===
SENTINEL="/tmp/pivota-setup-sentinel"
LOCK_FILE_PATH="backend/pom.xml"
INSTALL_PRESENCE_CHECK="$HOME/.m2/repository"
INSTALL_CMD='cd backend && mvn dependency:resolve -B -q'

run_install() {
  echo "[pivota] running install: $INSTALL_CMD"
  bash -c "$INSTALL_CMD"
}

if [[ -n "$LOCK_FILE_PATH" && -f "$LOCK_FILE_PATH" ]]; then
  CURRENT_HASH=$(sha256sum "$LOCK_FILE_PATH" | cut -d' ' -f1)
  PREVIOUS_HASH=$(cat "$SENTINEL" 2>/dev/null || echo "")

  PRESENCE_OK=1
  if [[ -n "$INSTALL_PRESENCE_CHECK" && ! -e "$INSTALL_PRESENCE_CHECK" ]]; then
    PRESENCE_OK=0
  fi

  if [[ "$CURRENT_HASH" == "$PREVIOUS_HASH" && "$PRESENCE_OK" == "1" ]]; then
    echo "[pivota] lockfile unchanged AND install output present; skipping install"
  else
    if [[ "$PRESENCE_OK" == "0" ]]; then
      echo "[pivota] install output ($INSTALL_PRESENCE_CHECK) missing; install required"
    else
      echo "[pivota] lockfile changed (or first boot); install required"
    fi
    run_install
    echo "$CURRENT_HASH" > "$SENTINEL"
  fi
elif [[ -n "$INSTALL_CMD" ]]; then
  if [[ ! -f "$SENTINEL" ]]; then
    run_install
    touch "$SENTINEL"
  fi
fi

# === D-14: retry loop (3 attempts, exponential backoff 1s / 2s / 4s) ===
EXEC_CMD='cd backend && mvn spring-boot:run -Dspring-boot.run.jvmArguments="-Dserver.address=0.0.0.0"'
ATTEMPT=1
DELAY=1
while (( ATTEMPT <= 3 )); do
  echo "[pivota] attempt $ATTEMPT: $EXEC_CMD"
  if bash -c "$EXEC_CMD"; then
    echo "[pivota] inner command exited 0; propagating success"
    exit 0
  fi
  EXIT_CODE=$?
  if (( ATTEMPT == 3 )); then
    echo "[pivota] all 3 attempts failed (last exit=$EXIT_CODE); surfacing failure"
    exit "$EXIT_CODE"
  fi
  echo "[pivota] attempt $ATTEMPT failed (exit=$EXIT_CODE); retrying in ${DELAY}s"
  sleep "$DELAY"
  DELAY=$(( DELAY * 2 ))
  ATTEMPT=$(( ATTEMPT + 1 ))
done

# Unreachable, but keep for analyzer happiness
exit 1
# === END PIVOTA PREAMBLE ===
# Below this marker, projects may add custom shutdown / setup logic.
# This region is PRESERVED across regenerations (plan 06's regen logic detects
# the marker and re-appends user content verbatim after re-emitting the preamble).
